---
name: CI

on:
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Setup Go env
        uses: actions/setup-go@v1
        with:
          go-version: "1.17.6"
      - name: Run fmtcheck
        run: make fmtcheck

  testacc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Setup Go env
        uses: actions/setup-go@v1
        with:
          go-version: "1.17.6"
      - name: Run acceptance tests
        run: make testacc
